/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SearchResult {
  title: string
  url: string
  snippet: string
  publishedDate?: string
  isPublicDomain: boolean
  id: string
  domain: string
}
export interface BatchSearchItem {
  query: string
  results: Array<SearchResult>
  error?: string
}
export interface BatchSearchResult {
  total: number
  successful: number
  failed: number
  items: Array<BatchSearchItem>
}
/** 执行单个搜索查询 */
export declare function kiroSearch(query: string, maxResults?: number | undefined | null): Promise<Array<SearchResult>>
/** 批量并发搜索 */
export declare function kiroBatchSearch(queries: Array<string>, maxResultsPerQuery?: number | undefined | null): Promise<BatchSearchResult>
